from credo_cf.classification.artifact.hot_pixel import hot_pixel
from credo_cf.classification.artifact.near_hot_pixel import near_hot_pixel
from credo_cf.classification.artifact.near_hot_pixel2 import near_hot_pixel2
from credo_cf.classification.artifact.too_often import too_often
from credo_cf.classification.artifact.too_bright import too_bright
